### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by wasauce** [hemanthsagarb/MM-ForecastIO#1]
1. I think the user needs to download the latest version of magicmirror and run npm install after updating the packages.

2. I also needed to upgrade to the latest npm and latest magicmirror.

2. Can you clean the code in the README so it can be more easily copy pasted into a config?

Awesome!

@hemanthsagarb

**Comment by hemanthsagarb** [comment]
1. Can you check the latest Readme once and see if that is enough
2. Also, please see the screenshot with updated summaries on colour bar
3. If you can provide the latest pic on Magic Mirror, I will put that too (or you can add) @wasauce

**Comment by wasauce** [comment]
@hemanthsagarb - Replied over email!
